[package]
authors = ["ZeroTier, Inc. <contact@zerotier.com>", "Adam Ierymenko <adam.ierymenko@zerotier.com>", "Monica Moniot <monica.moniot@zerotier.com>"]
edition = "2021"
license = "MPL-2.0"
name = "zssp-proto"
version = "0.1.0"

[lib]
name = "zssp_proto"
path = "src/lib.rs"
doc = true

[features]
default = ["debug"]
logging = []
debug = ["logging"]


[dependencies]
rand_core = "0.6.4"

pqc_kyber = { version = "0.6.0", default-features = false, features = ["kyber1024", "std"] }
aes-gcm = "0.10.2"
aes = "0.8.3"
p384 = "0.13.0"
sha2 = "0.10.7"
hmac = "0.12.1"
